version: "3"
services:
  service_nginx:
    container_name: nginx
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ~/nginx:/etc/nginx/conf.d
    links:
      - service_music
    privileged: true
    depends_on:
      - service_music
  service_music:
    container_name: music
    restart: always
    image: asd285653184/music
    expose:
      - "8020"
    ports:
      - "8020:8020"
    command: sh -c "cd /app/musicserver && npm run dev"
    privileged: true